// Generated by Wrangler on Sun Jun 09 2024 12:02:43 GMT-0600 (Mountain Daylight Time)
// by running `wrangler types`

interface Env {
  GITHUB_PAT: string;
  FULL_CONTACT_KEY: string;
  RESUME_CONTACT_EMAIL: string;
  RESUME_CONTACT_PHONE: string;
}
